###
GET http://localhost:3000/curso
###
POST http://localhost:3000/curso HTTP/1.1 
Content-Type: application/json

{  
    "id": 2,  
    "title": "Laravel"
}

###
PUT http://localhost:3000/curso/2 HTTP/1.1 
Content-Type: application/json

{   
    "title": "Tormenta 3"
}
###
DELETE  http://localhost:3000/curso/2 HTTP/1.1